metasfresh/metasfresh-e2e

- Dockerfile
- cypress/integration/misc/tab_internal_name_spec.js
- cypress/integration/product/product_set_documentnote.js
- cypress/integration/product/product_translation_spec.js
- cypress/integration/sales/sales_order_spec.js
- cypress/integration_defunct/sales/sales_order_spec.js
- cypress/page_objects/page.js
- cypress/page_objects/sales_orders.js
- cypress/support/apiRequests.js
- cypress/support/commands.js
- cypress/support/index.js
- cypress/support/utils/discountschema.js
- package.json
Cleanup and try the PageObject pattern for cypress tests.
**IMPORTANT**
This has to be run against a `metasfresh-frontend` with https://github.com/metasfresh/metasfresh-webui-frontend/pull/2234 merged .
You can use https://dev378.metasfresh.com/ for this purpose.
> Introduce PageObject pattern

- README.md
- cypress/integration/dataEntry/dataEntry_bpartner_spec.js
- cypress/integration/serialletter/serialletter.js
- cypress/integration_defunct/dataEntry/dataEntry_bpartner_spec.js
- cypress/integration_defunct/purchase/purchase_create_vendor_spec.js
- cypress/support/commands.js
- cypress/support/index.d.ts
- cypress/support/utils/bpartner.js
- cypress/support/utils/dataEntryGroup.js
- package.json
* push the current status in commands.js;
* @siemiatj the parts i struggle with are at
* serialletter.js line 48
* commands.js lines 176 and 481
* also:
* start using unique alias names
* prettier improvements
* additions to index.d.ts
* additiona to the README.md
* add license and repository to package.json
https://github.com/metasfresh/metasfresh-e2e/issues/16
> 16-e2e - Make our custom input commands more stable

- cypress/integration/dataEntry/dataEntry_set_seqno.js
- cypress/support/commands.js
- cypress/support/utils/dataEntryGroup.js
Related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/2214
> Fix data entry test

- cypress/integration/dataEntry/pricesystem_pricelist_plv_setup_spec.js
Create a new Pricesystem and Pricelist with PLV
> #14 Create Pricing Masterdata for Automatic End2End Tests with cypress

- cypress/fixtures/purchase/simple_vendor.json
- cypress/integration/purchase/purchase_create_simple_vendor_spec.js
- cypress/integration_defunct/product/product_set_documentnote.js
- cypress/support/utils/bpartner.js
* created a BPartner in a "temporary" spec, and used cy.writeFile to store its JSON to file simple_vendor.json
* add spec file purchase_create_simple_vendor_spec.js which
* loads the JSON into a BPartner instance
* overwrites the name
* and applies it
https://github.com/metasfresh/metasfresh-e2e/issues/34
> 34-e2e - Use fixtures for business objects

- .eslintrc
https://github.com/metasfresh/metasfresh-e2e/issues/37
> Adds auto lf to eslint config #37

- cypress/support/commands.js
https://github.com/metasfresh/metasfresh-e2e/issues/47
Can be used with cy.isChecked(fieldname, modal)
> Custom command for read-only checkbox #47

- cypress/integration/misc/paymentterm_setup_spec.js
> #45 Create test: Payment term

- cypress/fixtures/product/simple_product.json
- cypress/integration/product/productcategory_product_setup_spec.js
- cypress/support/utils/product.js
https://github.com/metasfresh/metasfresh-e2e/issues/40
> Use fixtures for products

- .babelrc
- cypress/fixtures/purchase/cypress_vendor.json
- cypress/fixtures/sales/sales_order.json
- cypress/integration/sales/__snapshots__/sales_order_spec.js.snap
- cypress/integration/sales/sales_order_spec.js
- cypress/page_objects/sales_order.js
- cypress/support/apiRequests.js
- cypress/support/commands.js
- cypress/support/utils/product.js
- cypress/support/utils/sales_order.js
- snapshots.js
- src/actions/AppActions.js
- src/services/Auth.js
- webpack.config.js
Related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/2241
> Fix sales order tests & add quick input test

- cypress/integration/sales/sales_order_spec.js
- cypress/support/index.js
> Login and save session before tests run

- cypress/support/commands/form.js
This has to come after https://github.com/metasfresh/metasfresh-webui-frontend/pull/2257
Related to #58
> Fix isChecked

- cypress/fixtures/currency/currency.json
- cypress/integration/currency/currency_activate_spec.js
- cypress/support/commands/form.js
- cypress/support/utils/currency.js
Implementing Test for activating/ deactivating Currency. Prepared the ground for further detailed Tests via fixture and currency object.
https://github.com/metasfresh/metasfresh-e2e/issues/76
> Set currency USD active/inactive #76

- cypress/fixtures/misc/notifications.json
- cypress/integration/misc/notifications_test.js
- cypress/support/COMMANDS.md
- cypress/support/commands/general.js
- webpack.config.js
> Helpers & test for notifications

- cypress/fixtures/product/simple_product.json
- cypress/integration/sales/sales_order_to_invoice_spec.js
- cypress/support/COMMANDS.md
- cypress/support/commands/form.js
- cypress/support/commands/general.js
- cypress/support/commands/navigation.js
- cypress/support/utils/product.js
> Changes to notifications commands and fixes for test

- cypress/integration/misc/sysconfig.js
- cypress/support/commands/navigation.js
- cypress/support/functions/index.js
Added a way to force clicks in click commands while working on this. Not super happy with hacking like that, but for some reason I can't find an element that would like to scroll properly.
Related to #87
> Fix test with filters

- cypress/fixtures/user/user.json
- cypress/integration/misc/user_spec.js
- cypress/page_objects/users.js
- cypress/support/commands/form.js
- cypress/support/utils/user.js
- package.json
> Tests for creating users

- cypress/integration/product/product_packing_item_setup.js
#26 Create Test: set packing item in product window
> #26 Create Test: set packing item in product window

- cypress/integration/masterdata/bpartner_group_spec.js
new bpartner group and adding a bpartner
> #70 Create new bpartner group

- cypress/fixtures/finance/bank.json
- cypress/fixtures/sales/simple_customer.json
- cypress/integration/settings/create_bank_and_set_it_to_bpartner.js
- cypress/support/utils/bank.js
- cypress/support/utils/bpartner.js
https://github.com/metasfresh/metasfresh-e2e/issues/72
> 72 Create new bank

- cypress/fixtures/material/quality_note.json
- cypress/integration/materialReceipt/create_quality_note.js
- cypress/support/utils/qualityNote.js
https://github.com/metasfresh/metasfresh-e2e/issues/127
> 127 Create quality note

- cypress/fixtures/finance/cost_center.json
- cypress/integration/finance/create_cost_center.js
- cypress/support/utils/bpartner.js
- cypress/support/utils/cost_center.js
https://github.com/metasfresh/metasfresh-e2e/issues/124
> 124 Create new Cost Center

- cypress/fixtures/product/bill_of_material.json
- cypress/integration/product/create_bill_of_material.js
- cypress/integration/product/product_for_procurement_contracts.js
- cypress/support/utils/billOfMaterial.js
- cypress/support/utils/product.js
https://github.com/metasfresh/metasfresh-e2e/issues/71
> 71 Create new BOM

- cypress/integration/inventory/inventory_aggregatedHUs_spec.js
- cypress/integration/inventory/inventory_default_doctype_spec.js
- cypress/integration/inventory/inventory_singleHU_spec.js
- cypress/integration/misc/bpartner_bpartner_relation_setup_spec.js
- cypress/integration/misc/paymentterm_setup_spec.js
- cypress/integration/product/create_bill_of_material.js
- cypress/support/COMMANDS.md
- cypress/support/commands/form.js
- cypress/support/index.d.ts
- cypress/support/utils/bpartner.js
- cypress/support/utils/currency.js
- cypress/support/utils/dataEntryField.js
- cypress/support/utils/dataEntrySection.js
- cypress/support/utils/dataEntryTab.js
- cypress/support/utils/product.js
It didn't work when field was disabled.
Related to #160
> Fix isChecked command

- cypress/integration/finance/create_GL_journal_line_entry_spec.js
> test completed as requested

- README.md
- run_cypress.sh
- run_docker_via_jenkins/Jenkinsfile
see https://docs.cypress.io/guides/guides/command-line.html#cypress-run-spec-lt-spec-gt
> optionally support the `--spec` cli parameter

- cypress/integration/sales/credit_memo_deliver_difference_for_sales_invoice.js
- cypress/support/index.d.ts
https://github.com/metasfresh/metasfresh-e2e/issues/135
> Create credit memo deliver difference for sales invoice

- cypress/fixtures/misc/misc_dictionary.json
- cypress/integration/sales/adjustment_charge_price_difference_for_sales_invoice.js
- cypress/support/utils/constants.js
https://github.com/metasfresh/metasfresh-e2e/issues/190
> Create Adjustment Charge (Nachbelastung Preisdifferenz) for sales invoice

- cypress/integration/sales/adjustment_charge_price_difference_for_sales_invoice.js
- cypress/integration/sales/adjustment_charge_quantity_difference_for_sales_invoice.js
https://github.com/metasfresh/metasfresh-e2e/issues/189
> Create Nachbelastung Mengendifferenz for sales invoice

- cypress/integration/sales/sales_order_api.spec.js
- cypress/support/utils/sales_order_api.js
- cypress/support/utils/utils.js
> Sales order API creation

- cypress.json
- cypress/integration/logistics/open_handling_unit_editor.js
- cypress/integration/sales/sales_order_to_shipment_to_invoice.js
https://github.com/metasfresh/metasfresh-e2e/issues/125
> #125 Open Handling Unit Editor

- cypress/integration/sales/sales_order_to_shipment_to_invoice.js
https://github.com/metasfresh/metasfresh-e2e/issues/137
> #137 Sales order to shipment to invoice

- cypress/integration/sales/sales_order_to_shipment_to_invoice.js
https://github.com/metasfresh/metasfresh-e2e/issues/137
> 137  Sales order to shipment to invoice

- cypress/fixtures/SPV fixtures/bpartner_group_SPV_Daily.json
SPV specific fixture for creating bpartner group; fixture only
> #1805 SPV fixture bpartner group

- cypress/integration/purchase/credit_memo_for_purchase_invoice.js
- cypress/integration/sales/change_shipment_date_shipment_schedule.js
- cypress/integration/sales/credit_memo_for_sales_invoice.js
- cypress/integration/sales/sales_order_api.spec.js
- cypress/integration/sales/sales_order_to_shipment_to_invoice.js
- cypress/support/utils/purchase_invoice.js
- cypress/support/utils/utils.js
https://github.com/metasfresh/metasfresh-e2e/issues/162
> Create credit memo Vendor (Lieferant)

- cypress/fixtures/product/packing_instructions.json
- cypress/fixtures/product/packing_instructions_version.json
- cypress/fixtures/product/packing_material.json
- cypress/integration/payment/create_manual_payment.js
- cypress/integration/purchase/purchase_order_material_receipt_invoice.js
- cypress/integration/sales/change_shipment_date_shipment_schedule.js
- cypress/integration/sales/credit_memo_for_sales_invoice.js
- cypress/page_objects/purchase_orders.js
- cypress/support/commands/form.js
- cypress/support/utils/builder.js
- cypress/support/utils/packing_instructions.js
- cypress/support/utils/packing_instructions_version.js
- cypress/support/utils/packing_material.js
- cypress/support/utils/pricelist.js
- cypress/support/utils/product.js
https://github.com/metasfresh/metasfresh-e2e/issues/161
> #161 Purchase order to material receipt to invoice

- cypress/integration/misc/notifications_test.js
- cypress/support/commands/general.js
- cypress/support/index.d.ts
> Updates for notifications

- cypress/support/commands/test.js
https://github.com/metasfresh/metasfresh-e2e/issues/145
> #145 Purchase order from sales order

- cypress/support/commands/form.js
https://github.com/metasfresh/metasfresh-e2e/issues/210
> #210 Create material receipt with quality issue

- cypress/integration/a/create_empties_returns.js
- cypress/integration/empties/create_empties_returns.js
- cypress/support/commands/navigation.js
- cypress/support/commands/test.js
- cypress/support/index.d.ts
- cypress/support/utils/constants.js
https://github.com/metasfresh/metasfresh-e2e/issues/211
> Create Empties Returns #211

- cypress/fixtures/misc/misc_dictionary.json
- cypress/integration/purchase/purchase_order_complete_reactivate_complete.js
- cypress/integration/purchase/purchase_order_from_sales_order.js
- cypress/integration/sales/change_shipment_date_shipment_schedule.js
- cypress/support/commands/form.js
- cypress/support/utils/constants.js
https://github.com/metasfresh/metasfresh-e2e/issues/108
> #108 Create purchase order with orderline, complete / reactivate / complete again

- cypress/fixtures/logistics/tour.json
- cypress/fixtures/logistics/tourversion.json
- cypress/integration/logistics/create_tour_tour_version.js
- cypress/support/commands/form.js
- cypress/support/index.d.ts
- cypress/support/utils/tour.js
- cypress/support/utils/tour_version.js
https://github.com/metasfresh/metasfresh-e2e/issues/230
>  #230 Create new Tour and Tourversion

- cypress/integration/logistics/create_delivery_days.js
- cypress/integration/logistics/create_tour_tour_version.js
https://github.com/metasfresh/metasfresh-e2e/issues/232
> #232 Create Delivery Days 

- Dockerfile
- cypress/support/commands/form.js
- cypress/support/commands/general.js
- package.json
We can't be too strict on the values comparison as types are all over the place.
> Small fix for our response wait function

- cypress/fixtures/settings/shipper.json
- cypress/integration/settings/create_shipper_set_in_transportation_order.js
- cypress/support/utils/shipper.js
https://github.com/metasfresh/metasfresh-e2e/issues/229
> #229 Create new Shipper

- cypress/integration/materialReceipt/create_material_receipt_with_quality_issue.js
https://github.com/metasfresh/metasfresh-e2e/issues/248
> Create Disposal from Handling Unit Editor #248

- cypress/integration/payment/create_payment_without_invoice_selection.js
https://github.com/metasfresh/metasfresh-e2e/issues/175
> #175 Create new payment (without invoice selection) 

- cypress/integration/sales/open_picking_terminal_and_filter.js
- cypress/integration_defunct/sales/open_picking_terminal_and_filter.js
- cypress/support/commands/form.js
- cypress/support/commands/navigation.js
- cypress/support/functions/index.js
- cypress/support/index.d.ts
https://github.com/metasfresh/metasfresh-e2e/issues/291
> #291 Open Picking Terminal and filter for Date, Product and BPartner

- cypress/integration/logistics/materialentnahme_complete_HU.js
- cypress/support/functions/index.js
https://github.com/metasfresh/metasfresh-e2e/issues/308
> #308 Materialentnahme complete HU

- cypress/fixtures/currency/currencyrate.json
- cypress/integration/currency/create_currency_rate_spec.js
- cypress/support/utils/currencyrate.js
- passes locally
- passes on Jenkins: https://jenkins.metasfresh.com/job/ops/job/run_e2e_tests/598/console
> Test finished.

- cypress/integration/materialReceipt/create_material_receipt_with_quality_issue.js
- cypress/integration/purchase/create_vendor_return.js
- cypress/integration/purchase/purchase_order_material_receipt_invoice.js
- cypress/integration/sales/sales_order_to_shipment_to_invoice.js
- cypress/integration/warehouse/change_warehouse_in_material_receipt_candidate.js
- cypress/support/commands/action.js
- cypress/support/utils/constants.js
- cypress/support/utils/sales_order.js
https://github.com/metasfresh/me03/issues/2544
> #2544 Sales order to shipment to invoice is still failing 

- cypress/integration/aaaaaaaaaaa/pick_HUs_and_create_shipment.js
- cypress/integration/price/add_a_product_to_a_pricelist_schema_and_create_a_new_PLV.js
- cypress/integration/price/create_new_pricelist_version_using_pricelist_schema.js
- cypress/integration/product/create_bill_of_material.js
- cypress/integration/product/product_for_procurement_contracts.js
- cypress/integration/product/product_packing_item_setup.js
- cypress/integration/product/productcategory_product_setup_spec.js
- cypress/integration/purchase/purchase_order_complete_change_complete.js
- cypress/integration/purchase/purchase_order_complete_reactivate_complete.js
- cypress/integration/purchase/purchase_order_material_receipt_invoice.js
- cypress/integration/sales/change_shipment_date_shipment_schedule.js
- cypress/integration/sales/sales_order_to_shipment_to_invoice.js
- cypress/integration/sales/void_a_sales_invoice_then_invoice_the_billing_candidates_again.js
- cypress/support/commands/action.js
- cypress/support/commands/form.js
- cypress/support/commands/general.js
- cypress/support/commands/navigation.js
- cypress/support/index.d.ts
- cypress/support/index.js
- cypress/support/utils/constants.js
https://github.com/metasfresh/metasfresh-e2e/issues/288
> Pick HUs for a shipment schedule and create shipment (simple workflow)

- cypress/integration/inventory/create_disposal_from_handling_unit_editor.js
- cypress/integration/logistics/materialentnahme_complete_HU.js
- cypress/integration/materialReceipt/create_material_receipt_with_quality_issue.js
- cypress/integration/purchase/create_vendor_return.js
- cypress/integration/purchase/purchase_order_material_receipt_invoice.js
- cypress/integration/sales/sales_order_to_shipment_to_invoice.js
- cypress/integration/warehouse/change_warehouse_in_material_receipt_candidate.js
- cypress/support/commands/action.js
- cypress/support/index.d.ts
https://github.com/metasfresh/metasfresh-e2e/issues/309
> #309 Materialentnahme partial

- cypress/fixtures/system/boiler_plate.json
- cypress/fixtures/system/create_update_boiler_plate.json
- cypress/integration/system/create_update_boiler_plate.js
- cypress/support/commands/form.js
- cypress/support/index.d.ts
- cypress/support/utils/boiler_plate.js
https://github.com/metasfresh/metasfresh-e2e/issues/312
> #312 Create new boiler plate / update existing boiler plate

- cypress/fixtures/materialReceipt/mat_receipt_quality_issue_invoice_unchecking_indispute.json
- cypress/integration/materialReceipt/mat_receipt_quality_issue_invoice_unchecking_indispute.js
- cypress/integration/purchase/purchase_order_material_receipt_invoice.js
- cypress/integration_defunct/logistics/materialentnahme_complete_HUs.js
- cypress/support/commands/navigation.js
- cypress/support/index.d.ts
https://github.com/metasfresh/metasfresh-e2e/issues/345
> #345 Create material receipt with quality issue and invoice without unchecking In Dispute 

- cypress/fixtures/contracts/flatrate_conditions_material_tracking_spec.json
- cypress/integration/contracts/flatrate_conditions_material_tracking_spec.js
- cypress/integration/materialReceipt/mat_receipt_quality_issue_invoice_indispute_checked.js
- cypress/support/utils/contract_lagerKonferenz.js
https://github.com/metasfresh/metasfresh-e2e/issues/356
> #356 Update test flatrate_conditions_material_tracking_spec 

- cypress/fixtures/contract/storage_conferenceversion.json
- cypress/fixtures/contracts/flatrate_conditions_material_tracking_spec.json
- cypress/fixtures/logistics/create_delivery_days.json
- cypress/integration/logistics/create_delivery_days.js
- cypress/integration/logistics/materialentnahme_complete_HU.js
- cypress/support/utils/tour_version.js
https://github.com/metasfresh/me03/issues/2719
> #2719 Fix failing tests on jenkins 

- cypress/fixtures/tax/taxcategory.json
- cypress/fixtures/tax/taxcategory_activate_spec.json
- cypress/fixtures/tax/taxrate.json
- cypress/integration/tax/taxcategory_activate_spec.js
- cypress/integration/tax/taxrate_setup_spec.js
- cypress/support/utils/product_price.js
- cypress/support/utils/taxcategory.js
- cypress/support/utils/taxrate.js
Implements and fixes 
https://github.com/metasfresh/metasfresh-e2e/issues/74
https://github.com/metasfresh/metasfresh-e2e/issues/75
> Update and fix tests related to TaxRate and TaxCategory + other bugfix 

- cypress/integration/misc/pricesystem_pricelist_plv_setup_spec.js
- cypress/support/utils/bpartner_ui.js
- cypress/support/utils/pricelist.js
- cypress/support/utils/purchase_order.js
- cypress/support/utils/sales_order.js
https://github.com/metasfresh/metasfresh-e2e/issues/367
> Change M_PricingSystem_ID from `listField` to `lookupListField`

- package.json
e2e run instance : https://dev815.metasfresh.com/
cypress url: https://dashboard.cypress.io/#/projects/5yp4q1/runs/674/specs
> Upgrade cypress to v3.5.0
